replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

grafana.ini:
  server:
    root_url: "https://metrics.kwer.fr/grafana"
    serve_from_sub_path: true
  auth.anonymous:
    enabled: true
    org_role: admin
  auth:
    disable_login_form: true
