---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-pull-secret
  namespace: metrics
spec:
  encryptedData:
    htpasswd: AgDAWdR4mo7Tzdrk8nGUbh+aakSvovzUhavEeljqX9iMoX1vdCtgBDwVb7cYLwxYYgwhXUxEv2tZCYqmmabMWoZTDKEIVY0ZVSdkqunWKUjBdOZQwhVJFipk0uoOJbMSfQoihNqBDYKo7EKiA6/nOzGjzoIU3RhiWw8ztsL3pRwOIcI4gSpvmilTwiBcZ+NXLarp5z0zRaiAV26yOS65Rl9vjc1uys5cVp7CoJ742mDhZ1PjgvOGO44DiZAnJ7iXNOCBDV/URBODCQKn99YiEee11znSoN1LK+Ty+7T7k+fUaDAOkZwSlXHYJYS3FYYyeMKHkcOF4P0l8WD4trefqaY6MfjOpdA+INGbM4ITeT6YsqDjvCe2w4v8J9vR+FrsjEQUzXFGX3HRokp07pYSOEddQyYvCA0f/EubplHraeGwenXsMqXWBYevVS7z51SDNtyZ8t+YnrtJ96rjhhwnXbIcIu39OeS/pL6mE6BsQVNBD9rChoXQkZW2Qrnjc1ECwLQqBaG57iCdcne6XTRFEYcUGDwuWQ9CZ1B22xuFfxKsIW0EgKTA16b2jZ4laMNrZBk3CR7VVhPOhvJhotYgwUCyML/LP3DGlzyIjQy8+b99+CsmxUmab3P5bbHSFSKMmDqlBLr3GiAwWQApLQwI6fAO9WlDM6Kn3F5F8SRFlgDLSOvQn6iQeDsz+lLtgG2HLwJr4Cecx2cGQv+w1qu2p34KLPzQa5s7woHQNOegl12fWIWkcp7J2ZxtmJJaKtp4Kfb6xdbCmDemWdAsGYknEQgosPAnbg==
  template:
    metadata:
      creationTimestamp: null
      name: registry-pull-secret
      namespace: metrics
    type: Opaque
