---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-pull-secret
  namespace: sample-app-prod
spec:
  encryptedData:
    .dockerconfigjson: AgAI2ssGv4aRb+x65b4SCJ/gTChS5k2y+3lka/O5r8/C65pgop31fYysQjiNxDg7/R/33QiKTzO2290N9GD91djuR8pJBUvZO0FVDWfDDBVGQPwJJSa5TTdUou79KpeJiL0izH/rHC11ta5/uqz2HHb3U6gMAbWbAVk3JRcC7aX4CA9kTtC5UNhbR8rwIPnEF2PHpKZ5KKCa2XQTZ4iZxjN/AanLx2ReJ37cN1ecBcFklReHVKfBxX7MIUIrfryDmo6YNJzI4ZDe+ZS9rGRa+IkyyiY/1SnZbIuQF9I55aZPiF/emXozQrIoINrqV46RQ6gBtqan8sHtY/fEEycZz3rPdzg42QcM9/LcpAz3jDhoytdBDpKzxh+zkb3WiKoKYMdod4wBIB6MzCzMwUoQIFt0TO6oO4rCoRKFHfCtDaLDk6iNnSQC6cRWBE3B4WU60vM/BwZQP6KgVV0MUbcbrFn33JRgkCSRYwa8zZzdoWd39NcAN41Jl4IxF5upsVnks2EzjJVmpNBOpxtb0mTBpLBZTC1aGatXMgDHTHUkg5l/vsfRDjDPV74FU/h09p5eTPAHE27DRNHE+zTOWP5ZrFFz3OO6Ujx8zOBhM2lsuNgeHfcn5weK1+9PVb6hIMwZAn2K8+PNn5n1RhwszpVhO6JgFXzW4xAFP9WNiahuEc/ok07lbTtyh/XYKkteXBPaN5ngI971bmxrlcd7YLEjoinVjGGhDeDgBs5QFGBWqtxDNk0WShfCaWb3OwK0dGWEqzEi30oVm2cltb2UVczRhsONN1U/0fqcBb/Aw66tukzKKHMEnFqrcEvdVXrb5GT8FIYGkSE07hwjOphnH0u/1pkzS5wtdjMBwIXU+2AwJVvRKKeU/6ro1HewDqgkn31+X75fZG4mcAkFzxZ9PA==
  template:
    metadata:
      creationTimestamp: null
      name: registry-pull-secret
      namespace: sample-app-prod
    type: kubernetes.io/dockerconfigjson
