---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-pull-secret
  namespace: metrics
spec:
  encryptedData:
    .dockerconfigjson: AgAOBy9LXZMQMX/w3QeI9BWvhYOMsuSRzOtKMoybd8wKC+vAxFUR0wd/fV1VhNoULvfLf7DE6lcTAfPeijrSiAFdyCzQMc6xmsJdkkIvIx5OrDaruTA1k08AMpVWrHsKwYfnGdMZHfGqL+txDJ1dxivd3DGF0EeJx6/BowXpO/FY//YDD8dH/0/7krFMt0IdiKX72bmom5ReceMD/WsRRkaq6znkpOD6wTCy6f1I6BaCasji4vRzs/dTeO25iOUvLnxu9pMvt9ou5AOwuElDNffnSJ/QRSbJM5PU85O2kDRAAQc8n5gyDCLszXb/faREESmNDk/DqmvZpyOLPVGvRn6Fbz4Oq1SuWDEtjAjgpuKulQwcm95vnKXCxBtHrQAaPOy2LV9Qfam2zBZEV24FZk09LkJ5bvD5LeftHq/IIxfl+1ZSMZn/kZuXs+SxqGawP/oPurur63ZudyhnEarA9zsUN8PBp7002fGdS1LFoqICyRgOCXDDaPoMBAqzG4sfM+OLYSTwbTaXW0NCLA/oCIh+f6+pCCmQ4srz/F/q/kxmZtxW8o7EtrDw/Djjc6YKTx8FnF5lMlUHUoNK1qLBA4KjnoWsFIiJq4g3dst0taa9bT91yVQjJnAeXThORuFPNzuoowxcIIbxq0vJ9FDopfFeLYv73Z4ZJVADBiEwhmz4gG4NqrojtSVTbGCjpe0vp9dlB4Ifu7XPrk/o1qltbkZvLPDlAMTkLWJ+Dz8KxbzRNENSXlZBAZiIJfHsbO4aPkGKEI34hcXTI/wtLdfj+PxxBX39kcNT2FpWLWP8rxhT+Y1guaMpHEOTGAb46UIKkyMGnwBq9z4vbE4D8eoYtabb5ZGy0YkGUMPASkUm33atPVFwVGMWx8ZGVhmDfCTL1z69gpY7oz9CcXGf1A==
  template:
    metadata:
      creationTimestamp: null
      name: registry-pull-secret
      namespace: metrics
    type: kubernetes.io/dockerconfigjson
