---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-pull-secret
  namespace: metrics
spec:
  encryptedData:
    htpasswd: AgAfM6nqj8QmTlBFhYsJYNFOpYBwTR04CPC46Uz7IqsA8hmuyEP2kIAzjvlyHwVitt/vnm8ddOINZYs2AZcvGZrbXNo5PPXhs1W9/xUyXg4xgSnNmRF8LcTQrs4bLg3qVZ5Mc6WDXCTs7GYq2DHfGtLw931C2MI2heymHrF4NjcNsPyCIQfhoFVAU514v+oSTKANtgBFANJ0v6FJVbALKOQhqMY5TtDVdtf/lTjzp6K+pPJ6hnfCoa4Dh1xh+ni28gmesQEsUNncjyPdanDlbGz5kVnv4wccoU/WAi4meDsryCXS6KAlRE/R8HQrb2sXwmoEEtOSzWoL1veEox4t7dMKsywNmMqEcSshiEm7obqouyZOz627Sc9zo4pu9U1X1G7BPNPvVMDdGZiUrJfvgEzLo7/TxV83zxQWr4nSYUAha/fPLhbIcYdTSPAEZ53VY2N6dUc/HQVHwTJCy6m5R7i+qt/9U4Te+q9hNNZ7ZplhvmTV80s2bn5pskIwRaMez7NEaqK6yk8mRKA0naJyschSbNTNA3084YvXaSAz9JqJIonMw1BevNHBnAqYqk8upSSxrZZHOU/PZiBkvNUlj0QHtsXw3wfjYd2GQYZFY6h6qjT9OiXEpYj84w/sr1x0/ykN8k9EfVk38TG85E7VcRFm9EG9ObqTavm/pZycaFuBqiBq/zfiQ8DetaZFGWh7ehDhKLC7Vk8/jqvaPK3J0STLAgWnBtf3AqHiBRfdSooQZ1mR0wnm8YbXKR7K2+RQOjOpcZpfHvBNZT4sniUaxlURMrcrHQ==
  template:
    metadata:
      creationTimestamp: null
      name: registry-pull-secret
      namespace: metrics
    type: Opaque
