---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-pull-secret
  namespace: sample-app-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCjKtvxUXxlUZIABWZ7iT5db44+Danr4xz/C+dxMJfn1BqaEpHV5Abq85HM+DfUHRI8ZuXqMtXDOdrjSHNGucHNANl4yTFrWYERtOV62+Yt5+3v8FKqbbFEd8NVpZo2ZBuR8Z/qVQ23Ma69I/4Sn0OltFLpYNFH0GNeqeVe1EfFRQ8tFS8o3GjOR/w/cRih1s9Q5ocLpgnR2aI8TTno8lsC6D4kZYmS9CuGuF3SG6nziqb0H3gJS/H8B2812T4EZpiloFEvQdbxtUFaIQKBHxuSsCMtQsJhuAzB6Hr4vc3uG9FcnSzxb5V/1hy9HuR+KO0ItcY1QLLb9ELpi8TUOWZyPxlSKBnvcOxHOqhsGuRP1IdFE7TKWFWhmXTZXYF0tdJ9qRygT4njDovXqQYkvXmHre/x6MmKd7M7Kfh3DjTDOK/61mLL1LeQhha46Hjoif9cwtPxPFqUxWaUv+h7gyyTklJ/CT650dH3g+sk728Qenw5j/bro9D2YHHKNKCCbWIX6RGnhpiKItl5IMLU6hXugQsHV7FSTgxsDPKZ4WOKgYj9A0Gii+d7ufPe+QHC27UllXHXa7+qhxV03kSXWx2W8YUfWBcGO9d2hoOf9AzH/ZrLjRvqs6eyy9ZM5H4E9/ljEhHFzxGP6f2+q1jq/kbZqAlA18ZGtYO1/IB/vJaIWqhuwcHeQooz6jgunmdJV7xzX8r8J1ZvIspR42LH50+TyeATe8GjHC5wV1pbB6DSsdbj/L93M9jHNHrAWSCRUqbfAPR8rrQNiA/X3Aakgvf2j+uzoV7SqO6C82B+Zd8/dB31wBZt9TVrQbjapRH/qfCgSBB/frt4ZmdEBhoi9l/iw+kbdLheOA3upX9CvDDG8m7ntVVNWJm6baoIkr9FF/MjobcppPblOFvc1Q==
  template:
    metadata:
      creationTimestamp: null
      name: registry-pull-secret
      namespace: sample-app-dev
    type: kubernetes.io/dockerconfigjson
