image:
  repository: registry.kwer.fr/kubequest/dev/sample-app-master
  tag: 0.4.1

imagePullSecrets:
  - name: registry-pull-secret

ingress:
  enabled: false

httpRoute:
  enabled: true
  hostname: dev.kwer.fr

secret:
  create: false
  existingSecret: sample-app-env

migration:
  releaseId: 0.4.1
