image:
  repository: registry.kwer.fr/kubequest/dev/sample-app-master
  tag: 0.1.0-dev.a216dbf283a0

imagePullSecrets:
  - name: registry-pull-secret

ingress:
  enabled: false

secret:
  create: false
  existingSecret: sample-app-env

migration:
  releaseId: 0.1.0-dev.a216dbf283a0
