replicaCount: 2

image:
  repository: registry.kwer.fr/kubequest/prod/sample-app-master
  tag: 0.3.0

imagePullSecrets:
  - name: registry-pull-secret

ingress:
  enabled: false

httpRoute:
  enabled: true
  hostname: kwer.fr

secret:
  create: false
  existingSecret: sample-app-env

migration:
  releaseId: 0.3.0
