replicaCount: 2

image:
  repository: registry.kwer.fr/kubequest/prod/sample-app-master
  tag: latest

imagePullSecrets:
  - name: registry-pull-secret

ingress:
  enabled: false

secret:
  create: false
  existingSecret: sample-app-env
