deploymentMode: SingleBinary

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: longhorn-2-replicas
    accessModes:
      - ReadWriteOnce
    size: 2Gi

backend:
  replicas: 0

read:
  replicas: 0

write:
  replicas: 0

gateway:
  enabled: false

test:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: false
