---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-auth
  namespace: registry
spec:
  encryptedData:
    htpasswd: AgBJdDGJGCRTfW8G6jUiSz8JyuU55E27Bkx89WVsWTa0M1a0PTK/LZnRiq7RH5riZdIqTznAfC5EJzMlpqOOonfdEly0cm8kT5nVXMqV3M4mfMtocktqOgFEKhtUwgkoAjLe9l3QFmwCLdVN5m/nVF3W4NTOkZJYXqdB7qZK4TRWAjg5eqTFRuPXxtuGEHoR//Lx2o3LtaU/0aO67SBKwo1xB/eu7xhwyXgh0mlLu5TCIAI0NWEBWnMQ9OXLo0DUC3IPtgU+EDUH+XOWX9EQgoUBkQkEhF4+wDYbc+aFYM7izK6AGKD5GpnBvI/5I/6kKliILV3UiQCL+466UiZ5q1d2YXAFUsfath2vye5qzS1185sIX0D12esk9QHOJMZc2iIGh72QDfkvvR5U7HxkaWSSmMxbtUxKXJRgq6PQe3zVy2b5F7DrSTvg4RUG2bBLUoYRpTHy8ouCWhG1895pA7IFhvCUsUvhlUrSVcb9nOTn+b5wyEAHxXoSkLuYkJ/zlFVxCfyEI7zHHJQ0QXke7W9Sf+lNERdMAkmXCXz5C9xpZc7w3Bj981+8EF2BuA5AfngwLVEVSkUEToHTawO61gtiZuc8CDuPbUCvqpvJpYaD4lxEHiTkfjE5N3GAM2EZ6wC1wkuNI5XKWaGfU++ARqWkEEeYr1H1L11itLxG/LCmkOY1TWizDPCjEFMz1oVNUvgCssXht1za96qVgmBx/BGOcP4Xh7Jfb4Z1vvL7D3QfOGE0SXj6jUlakt052TwWIHTpxyZdEQ76+N4Hu/Qg5So3iaaG
  template:
    metadata:
      creationTimestamp: null
      name: registry-auth
      namespace: registry
    type: Opaque
