fullnameOverride: argocd

configs:
  params:
    server.insecure: true
    server.basehref: /argocd
    server.rootpath: /argocd

server:
  service:
    type: ClusterIP

  ingress:
    enabled: false
