upstream traefik_http {
    server master:30080;
    server ip-10-0-14-163.eu-west-3.compute.internal:30080;
    # server worker-2:30080;
    # server worker-3:30080;
    # server worker-4:30080;
    keepalive 32;
}
