---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: metrics-auth
  namespace: traefik
spec:
  encryptedData:
    htpasswd: AgDM61MTA99WPMkyRa3oxfCL+GqMjS+2P0p5gxLoqDEz2M5jPcn6XBl+jF7TNFg8XYCh0ifNgW+GKMX6tKV41V6zIru1ZKlkTsYeH1PCISkVSGBn1ZLAOK24qWuFGYqJHcehR30SJF4KC1edsyefpCAku7akoymmLNGmqmUFGZfz5fpUsf9yzXfbZazTvO/jIQsCEGIgT9ITZiYu6hobNf6vxlE9CiX0p3ZOgMWJcV/KNwYP2XQfDqWZZ5pDVsyBDZ+MkZkzbEm0uINSDvK7dl/8FVAdmKhGLNYPNBnL3IIigvTa4EaHVt0d7cKv6vd4+iHBY2GDKr4NGN3GoFYmA7RXGpb11gZW9a7OsQ6na7d/uhKw+IaLPwhEf8xC+yCSahIWfIhYXAgUGdjoQSTQzOooyUrlkbn35628kPzHoP9adEsG4BH+KYPgIqHGyAVJ32Y+GAVg9ocquSRt0rN7V9VmAXxhvFzmJ062dbrU/hKFR4G+9S2RhhQOqrjAghuTjhwIlqNNMer0vzq5L/31HHNJOnlS6VbKvJjIaSQAxPLApqImRWSCmCa0QeuV7+Z0HL9CXvaWv1Ni1z10WyDO/KVsddzheJo8ehBjPM1wvLN9olL5vAxizM2t4XOxgAxKdoRxp5swumL2NgrR2yl3Iw9/0UDHvFz8ssY4QR+AWJtRfM4YI5dLWIOiTOeR5VaxrPc8A1UN4ghDZehFUagAeQZV9qRob3IULEd7rbOEEXqgAFR+nbrBq4qFDHTEfV8Spdi8rn/VaGMbvl3srOK2qHOSN+ci
  template:
    metadata:
      creationTimestamp: null
      name: metrics-auth
      namespace: traefik
    type: Opaque
