server {
    listen 443 ssl;
    server_name registry.kwer.fr;

    location / {
        include /etc/nginx/conf.d/snippets/proxy-traefik.conf;
    }
}

server {
    listen 80;
    server_name registry.kwer.fr;

    return 301 https://$host$request_uri;
}
