server {
    listen 443 ssl;
    server_name whoami.kwer.fr;

    ssl_certificate /etc/letsencrypt/live/whoami.kwer.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/whoami.kwer.fr/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        include /etc/nginx/conf.d/snippets/proxy-traefik.conf;
    }
}

server {
    listen 80;
    server_name whoami.kwer.fr;

    return 301 https://$host$request_uri;
}
