apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pull-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/ratataque/kubequest
    targetRevision: main
    path: gitops/secrets
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
